steps:
  # Docker Build
  #  - name: 'gcr.io/cloud-builders/docker'
  #    args: ['build', '-t',
  #           'gcr.io/mawa-162022/github.com/raretag-za/mawa:$BRANCH_NAME',
  #           '.']
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - -c
      - |
        git config --global credential.helper '!f() { echo "username=x-access-token"; echo "password=$$github-token"; }; f'
        git clone https://github.com/mawa-za/flyway-scripts.git flyway-scripts

    secretEnv: [ 'github-token' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/mawa-162022/mawa-repo/mawa-bes:$BRANCH_NAME',
           '.']
  # Docker Push
  #  - name: 'gcr.io/cloud-builders/docker'
  #    args: ['push',
  #           'gcr.io/mawa-162022/github.com/raretag-za/mawa:$BRANCH_NAME']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/mawa-162022/mawa-repo/mawa-bes:$BRANCH_NAME']

availableSecrets:
  secretManager:
    - versionName: projects/mawa-162022/secrets/github-token/versions/latest
      env: github-token

options:
  logging: CLOUD_LOGGING_ONLY