steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/mawa-162022/mawa-repo/mawa-bes:$BRANCH_NAME',
        '--build-arg', 'GITHUB_TOKEN=$github-token',
        '.'
      ]
    secretEnv: ['github-token']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/mawa-162022/mawa-repo/mawa-bes:$BRANCH_NAME'
      ]

availableSecrets:
  secretManager:
    - versionName: projects/mawa-162022/secrets/github-token/versions/latest
      env: github-token

options:
  logging: CLOUD_LOGGING_ONLY
