steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/mawa-162022/mawa-repo/mawa-bes:$BRANCH_NAME',
           '.']
    secretEnv: ['GITHUB_TOKEN']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/mawa-162022/mawa-repo/mawa-bes:$BRANCH_NAME']

availableSecrets:
  secretManager:
    - versionName: projects/mawa-162022/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

options:
  logging: CLOUD_LOGGING_ONLY
