FROM maven:3.8.7-openjdk-18 AS build

# Pass GitHub token as a build argument
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

# Copy source
COPY src /home/app/src
COPY pom.xml /home/app

# Clone flyway scripts using PAT
RUN git clone https://x-access-token:${GITHUB_TOKEN}@github.com/mawa-za/flyway-scripts.git /home/app/src/main/resources/db/migration

# Build the project
RUN mvn -f /home/app/pom.xml clean install -Pdev

# Runtime image
FROM openjdk:latest
EXPOSE 8080
ARG JAR_FILE=/home/app/target/mawa-bes.jar
COPY --from=build ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
