# Stage 1: Build with Maven
FROM maven:3.8.7-openjdk-17 AS build

# Set working directory
WORKDIR /home/app

# Copy source code and pom
COPY src /home/app/src
COPY pom.xml /home/app/

# Clone Flyway scripts from master branch only
RUN mkdir -p /home/app/src/main/resources/db/migration \
    && git clone --branch beta --single-branch --depth 1 https://github.com/mawa-za/mawa-flyway-scripts.git /tmp/flyway-scripts \
    && cp -r /tmp/flyway-scripts/* /home/app/src/main/resources/db/migration/ \
    && rm -rf /tmp/flyway-scripts

RUN ls -R /home/app/src/main/resources/db/migration

# Build the application
RUN mvn clean install -Pbeta

# Stage 2: Runtime
FROM openjdk:17-jdk-slim

# Expose application port
EXPOSE 8080

# Copy JAR from build stage
ARG JAR_FILE=/home/app/target/mawa-bes.jar
COPY --from=build ${JAR_FILE} app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app.jar"]
