FROM maven:3.8.7-openjdk-18 AS build

# Build arg for GitHub token
ARG GITHUB_TOKEN

# Copy source code
COPY src /home/app/src
COPY pom.xml /home/app

RUN mkdir -p /home/app/src/main/resources/db/migration

# Clone Flyway scripts into resources
RUN git clone https://$GITHUB_TOKEN@github.com/mawa-za/flyway-scripts.git /home/app/src/main/resources/db/migration

# Build project
RUN mvn -f /home/app/pom.xml clean install -Pdev

# Runtime image
FROM openjdk:latest
EXPOSE 8080
ARG JAR_FILE=/home/app/target/mawa-bes.jar
COPY --from=build ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
