# Stage 1: Build
FROM maven:3.8.7-openjdk-18 AS build

# Set build arg for GitHub token
ARG GITHUB_TOKEN

# Copy pom first
COPY pom.xml /home/app

# Copy source code
COPY src /home/app/src

# Clone flyway scripts into the correct location
RUN git clone https://$GITHUB_TOKEN@github.com/mawa-za/flyway-scripts.git /home/app/src/main/resources/db/migration

# Build project
RUN mvn -f /home/app/pom.xml clean install -Pdev

# Stage 2: Run
FROM openjdk:18-jdk
EXPOSE 8080
ARG JAR_FILE=/home/app/target/mawa-bes.jar
COPY --from=build ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
