# Stage 1: Build
FROM maven:3.8.7-openjdk-18 AS build

# Set environment variable for GitHub token (passed as build-arg)
ARG GITHUB_TOKEN

# Clone flyway scripts into the right location
RUN git config --global credential.helper '!f() { echo "username=x-access-token"; echo "password=$GITHUB_TOKEN"; }; f' && \
    git clone https://github.com/mawa-za/flyway-scripts.git src/main/resources/db/migration

# Copy the rest of the app
COPY src /home/app/src
COPY pom.xml /home/app

# Build the application
RUN mvn -f /home/app/pom.xml clean install -Palpha

# Stage 2: Runtime
FROM openjdk:latest
EXPOSE 8080

ARG JAR_FILE=/home/app/target/mawa-bes.jar
COPY --from=build ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
