package za.co.mawa.bes.enums;

public enum ApprovalType {
    CLAIM,
    PAYMENT,
    LEAVE,
    CASHUP,
    INVOICE,
    PURCHASE_ORDER,
    JOURNAL,
    PAYMENT_REQUEST,
    SUPPLIER_INVOICE,
    CUSTOMER_REFUND,
    SUPPLIER_ONBOARDING,
    SUPPLIER_BANKING_DETAILS,
    MEMBERSHIP_TRANSFER,
    MEMBERSHIP_PLAN_CHANGE,
}

