package za.co.mawa.bes.enums;

public enum ApprovalType {
    CLAIM,
    PAYMENT,
    LEAVE,
    CASHUP,
    INVOICE,
    PURCHASE_ORDER,
    JOURNAL,
    PAYMENT_REQUEST,
    SUPPLIER_INVOICE,
    CUSTOMER_REFUND,
    SUPPLIER_ONBOARDING,
    SUPPLIER_BANKING_DETAILS,
    MEMBERSHIP_TRANSFER,
    MEMBERSHIP_PLAN_CHANGE,
    MEMBERSHIP_DEPENDENT_CHANGE,
    ADDITIONAL_MEMBERSHIP,
    PAYROLL_BATCH,
    EMPLOYEE_BANKING_DETAILS,
    FUNERAL_UNDERWRITING,
    FUNERAL_COVER_STATUS_CHANGE,
    GROUP_SOCIETY_STATUS_CHANGE,
    GROUP_SOCIETY_BALANCE_ADJUSTMENT,
    GROUP_SOCIETY_FUNERAL_CLAIM,
}

