spring.profiles.active=@spring.profiles.active@

spring.mail.host = smtp.office365.com
spring.mail.username = noreply@mawa.co.za
spring.mail.password = Mah91991
spring.mail.port = 587
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.from=noreply@mawa.co.za
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.socketFactory.fallback = true
spring.mail.properties.mail.mail.debug=true
#spring.mail.properties.mail.pop3.host=pop email address
#spring.mail.properties.mail.pop3.port=110
#spring.mail.properties.mail.pop3.starttls.enable=true
#spring.mail.properties.mail.pop3.store=pop3s
#spring.mail.properties.pop.pop3.username=pop username
#spring.mail.properties.pop.pop3.password=pop password
#spring.mail.properties.pop.pop3.folder=INBOX
mail.from.name=Mawa