server.port = 8080
application.version = @project.version@

server.servlet.context-path=/api/v1

jwt.secret=Rrtg@6365
jwt.expirationDateInMs=9000000
jwt.refreshExpirationDateInMs=9000000

#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.multiTenancy=DATABASE
spring.jpa.properties.hibernate.tenant_identifier_resolver=za.co.raretag.mawabes.configuration.hibernate.TenantIdentifierResolver
spring.jpa.properties.hibernate.multi_tenant_connection_provider=za.co.raretag.mawabes.configuration.hibernate.DatabaseMultiTenantConnectionProvider

spring.datasource.url=${hibernate.connection.url}
spring.datasource.username=${hibernate.connection.username}
spring.datasource.password=${hibernate.connection.password}

hibernate.connection.url=jdbc:mysql://localhost:3306/mawa-admin
hibernate.connection.username=root
hibernate.connection.password=Yles@4izar
hibernate.default_schema=mawa-admin
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver

flyway.url=${hibernate.connection.url}
flyway.user=${hibernate.connection.username}
flyway.password=${hibernate.connection.password}
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=false