hibernate.connection.url=jdbc:mysql://35.184.235.103:3306/mawa
hibernate.connection.username=root
hibernate.connection.password=Rrtg@6365
hibernate.default_schema=mawa
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver