hibernate.connection.url=jdbc:mysql://104.154.200.191:3306/mawa
hibernate.connection.username=root
hibernate.connection.password=Rrtg@6365
hibernate.default_schema=mawa
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver